# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='policepost',
            name='hood',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='PolicePost',
        ),
    ]
