# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighbourr',
        ),
    ]
